/**
 * Test App API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Author { 
    readonly id?: number;
    readonly url?: string;
    first_name: string;
    last_name: string;
    citizenship: string;
    date_of_birth?: string | null;
    date_of_death?: string | null;
}

