/**
 * Test App API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Book { 
    readonly id?: number;
    title: string;
    author?: number | null;
    publication_date: string;
    readonly created_at?: string;
    readonly updated_at?: string;
}

