/**
 * Test App API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Book { 
    readonly id?: number;
    readonly url?: string;
    title: string;
    readonly author_name?: string;
    readonly author_url?: string;
    author?: number;
    publication_date: string;
    readonly year?: string;
    readonly created_at?: string;
    readonly updated_at?: string;
}

