/**
 * Library App API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Book } from './book';


export interface PaginatedBookList { 
    count: number;
    next?: string;
    previous?: string;
    results: Array<Book>;
}

