/**
 * Library App API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Book } from './book';


export interface PaginatedBookList { 
    total_records?: number;
    total_pages?: number;
    current_page?: number;
    next?: string;
    previous?: string;
    results?: Array<Book>;
}

