/**
 * Library App API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Author } from './author';


export interface PaginatedAuthorList { 
    total_records?: number;
    total_pages?: number;
    current_page?: number;
    next?: string;
    previous?: string;
    results?: Array<Author>;
}

