/**
 * Test App API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Book } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface CreateBookRequestParams {
    book?: Book;
}

export interface DestroyBookRequestParams {
    id: string;
}

export interface PartialUpdateBookRequestParams {
    id: string;
    book?: Book;
}

export interface RetrieveBookRequestParams {
    id: string;
}

export interface UpdateBookRequestParams {
    id: string;
    book?: Book;
}


export interface LibraryServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * A viewset for viewing and editing book instances.  This viewset provides &#x60;list&#x60;, &#x60;create&#x60;, &#x60;retrieve&#x60;, &#x60;update&#x60; and &#x60;destroy&#x60; actions for the Book model.
* @param requestParameters
     */
    createBook(requestParameters: CreateBookRequestParams, extraHttpRequestParams?: any): Observable<Book>;

    /**
     * 
     * A viewset for viewing and editing book instances.  This viewset provides &#x60;list&#x60;, &#x60;create&#x60;, &#x60;retrieve&#x60;, &#x60;update&#x60; and &#x60;destroy&#x60; actions for the Book model.
* @param requestParameters
     */
    destroyBook(requestParameters: DestroyBookRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * A viewset for viewing and editing book instances.  This viewset provides &#x60;list&#x60;, &#x60;create&#x60;, &#x60;retrieve&#x60;, &#x60;update&#x60; and &#x60;destroy&#x60; actions for the Book model.
*/
    listBooks(extraHttpRequestParams?: any): Observable<Array<Book>>;

    /**
     * 
     * A viewset for viewing and editing book instances.  This viewset provides &#x60;list&#x60;, &#x60;create&#x60;, &#x60;retrieve&#x60;, &#x60;update&#x60; and &#x60;destroy&#x60; actions for the Book model.
* @param requestParameters
     */
    partialUpdateBook(requestParameters: PartialUpdateBookRequestParams, extraHttpRequestParams?: any): Observable<Book>;

    /**
     * 
     * A viewset for viewing and editing book instances.  This viewset provides &#x60;list&#x60;, &#x60;create&#x60;, &#x60;retrieve&#x60;, &#x60;update&#x60; and &#x60;destroy&#x60; actions for the Book model.
* @param requestParameters
     */
    retrieveBook(requestParameters: RetrieveBookRequestParams, extraHttpRequestParams?: any): Observable<Book>;

    /**
     * 
     * A viewset for viewing and editing book instances.  This viewset provides &#x60;list&#x60;, &#x60;create&#x60;, &#x60;retrieve&#x60;, &#x60;update&#x60; and &#x60;destroy&#x60; actions for the Book model.
* @param requestParameters
     */
    updateBook(requestParameters: UpdateBookRequestParams, extraHttpRequestParams?: any): Observable<Book>;

}
